In [1]:
import pandas as pd
import numpy as np

In [2]:
df_simulation_store_product = pd.read_json('simulation_store_product.json', lines = True)

In [52]:
df_simulation_store_product_agg = df_simulation_store_product[
    (df_simulation_store_product['LUNAR_DAY'] >= 21)
    & (df_simulation_store_product['VALUE_ACTUAL_BASE_SALE_QTY'] > 0)
].groupby(['CITY', 'STORE_ID', 'PRODUCT_ID'])[['VALUE_ACTUAL_BASE_SALE_QTY', 'VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityLunarDay', 'VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions']].sum().reset_index().sort_values(by = ['VALUE_ACTUAL_BASE_SALE_QTY'], ascending = False)

df_simulation_store_product_agg['MAPE_byMCH5CityLunarDay'] = abs(df_simulation_store_product_agg['VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityLunarDay'] - df_simulation_store_product_agg['VALUE_ACTUAL_BASE_SALE_QTY']) / df_simulation_store_product_agg['VALUE_ACTUAL_BASE_SALE_QTY'] 
df_simulation_store_product_agg['MAPE_byMCH5CityStoreTransactions'] = abs(df_simulation_store_product_agg['VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions'] - df_simulation_store_product_agg['VALUE_ACTUAL_BASE_SALE_QTY']) / df_simulation_store_product_agg['VALUE_ACTUAL_BASE_SALE_QTY'] 

df_simulation_store_product_agg

,CITY,STORE_ID,PRODUCT_ID,VALUE_ACTUAL_BASE_SALE_QTY,VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityLunarDay,VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions,MAPE_byMCH5CityLunarDay,MAPE_byMCH5CityStoreTransactions
31803,HÀ NỘI,1535,10012012,27519.000,55067.004547,50725.335244,1.001054,0.843284
119605,HÒA BÌNH,1648,10012012,25903.000,10284.110681,10702.022973,0.602976,0.586842
31252,HÀ NỘI,1530,10167037,19447.000,328.483298,299.795015,0.983109,0.984584
32081,HÀ NỘI,1541,10012012,13883.000,16167.585441,14860.412976,0.164560,0.070404
36702,HÀ NỘI,1698,10167037,13035.000,7798.855621,7417.423361,0.401699,0.430961
...,...,...,...,...,...,...,...,...
122644,HƯNG YÊN,5706,10640295,0.016,0.180687,0.166587,10.292968,9.411707
61703,HÀ NỘI,3291,10640295,0.016,0.089387,0.098343,4.586714,5.146467
209701,QUẢNG NINH,4304,10640295,0.014,0.090174,0.062518,5.441028,3.465583
46732,HÀ NỘI,2371,10640295,0.012,0.000000,0.000000,1.000000,1.000000
95281,HÀ NỘI,5554,10640295,0.012,0.011593,0.009099,0.033914,0.241757

In [22]:
df_simulation_store_product_agg_top100stores = df_simulation_store_product_agg[df_simulation_store_product_agg['STORE_ID'].isin(df_simulation_store_product_agg.groupby(['STORE_ID'])['VALUE_ACTUAL_BASE_SALE_QTY'].sum().reset_index().sort_values(by = ['VALUE_ACTUAL_BASE_SALE_QTY'], ascending = False)[:100]['STORE_ID'].unique())]
df_simulation_store_product_agg_top100stores

,CITY,STORE_ID,PRODUCT_ID,VALUE_ACTUAL_BASE_SALE_QTY,VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityLunarDay,VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions
31803,HÀ NỘI,1535,10012012,27519.000,55067.004547,50725.335244
119605,HÒA BÌNH,1648,10012012,25903.000,10284.110681,10702.022973
31252,HÀ NỘI,1530,10167037,19447.000,328.483298,299.795015
32081,HÀ NỘI,1541,10012012,13883.000,16167.585441,14860.412976
36702,HÀ NỘI,1698,10167037,13035.000,7798.855621,7417.423361
...,...,...,...,...,...,...
218356,THANH HÓA,1598,10196002,0.414,0.000000,0.000000
234339,TÂY NINH,1615,10194793,0.270,0.970509,1.517580
120073,HÒA BÌNH,5373,10196001,0.104,0.032482,0.134412
36347,HÀ NỘI,1672,10196002,0.104,0.046457,0.037998
172452,HỒ CHÍ MINH,6228,10196002,0.094,0.200000,0.124315

In [26]:
df_simulation_store_product_agg_top100stores['MAPE_byMCH5CityLunarDay'] = abs(df_simulation_store_product_agg_top100stores['VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityLunarDay'] - df_simulation_store_product_agg_top100stores['VALUE_ACTUAL_BASE_SALE_QTY']) / df_simulation_store_product_agg_top100stores['VALUE_ACTUAL_BASE_SALE_QTY']

df_simulation_store_product_agg_top100stores['MAPE_byMCH5CityStoreTransactions'] = abs(df_simulation_store_product_agg_top100stores['VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions'] - df_simulation_store_product_agg_top100stores['VALUE_ACTUAL_BASE_SALE_QTY']) / df_simulation_store_product_agg_top100stores['VALUE_ACTUAL_BASE_SALE_QTY']

C:\Users\manhdt\AppData\Local\Temp\ipykernel_19564\3651634987.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_simulation_store_product_agg_top100stores['MAPE_byMCH5CityLunarDay'] = abs(df_simulation_store_product_agg_top100stores['VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityLunarDay'] - df_simulation_store_product_agg_top100stores['VALUE_ACTUAL_BASE_SALE_QTY']) / df_simulation_store_product_agg_top100stores['VALUE_ACTUAL_BASE_SALE_QTY']
C:\Users\manhdt\AppData\Local\Temp\ipykernel_19564\3651634987.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_simulation_store_product_agg_top100stores['MAPE_byMCH5CityStoreTransactions'] = abs(df_simulation_store_product_agg_top100stores['VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions'] - df_simulation_store_product_agg_top100stores['VALUE_ACTUAL_BASE_SALE_QTY']) / df_simulation_store_product_agg_top100stores['VALUE_ACTUAL_BASE_SALE_QTY']

In [33]:
df_forecast_agg_city_product_daily = pd.read_json('simulation_agg_city_product.json', lines = True)
df_forecast_agg_city_product_daily

,CITY,PRODUCT_ID,CALDAY,LUNAR_DATE,LUNAR_YEAR,LUNAR_MONTH,LUNAR_DAY,VALUE_ACTUAL_BASE_SALE_QTY,VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityLunarDay,VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions
0,HÀ NỘI,10011224,2020-01-12,2019-12-18,2019,12,18,535.0,NaN,NaN
1,HỒ CHÍ MINH,10601528,2020-01-12,2019-12-18,2019,12,18,735.0,NaN,NaN
2,ĐÀ NẴNG,10011290,2020-01-12,2019-12-18,2019,12,18,127.0,NaN,NaN
3,BÌNH DƯƠNG,10620866,2020-01-12,2019-12-18,2019,12,18,41.0,NaN,NaN
4,HỒ CHÍ MINH,10011214,2020-01-12,2019-12-18,2019,12,18,4697.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
841631,BẮC KẠN,10011289,2021-02-10,2020-12-29,2020,12,29,118.0,NaN,NaN
841632,TÂY NINH,10014262,2021-02-10,2020-12-29,2020,12,29,3.0,NaN,NaN
841633,KON TUM,10011214,2021-02-10,2020-12-29,2020,12,29,15.0,NaN,NaN
841634,BẮC KẠN,10190701,2021-02-10,2020-12-29,2020,12,29,4.0,NaN,NaN
841635,LẠNG SƠN,10012784,2021-02-10,2020-12-29,2020,12,29,3.0,NaN,NaN

In [44]:
df_simulation_city_product_agg = df_forecast_agg_city_product_daily[
    (df_forecast_agg_city_product_daily['VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions'] > 0)
    & (df_forecast_agg_city_product_daily['VALUE_ACTUAL_BASE_SALE_QTY'] > 0)
].groupby(['CITY', 'PRODUCT_ID'])[[
    'VALUE_ACTUAL_BASE_SALE_QTY', 'VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityLunarDay', 'VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions'
]].sum().reset_index().sort_values(by= ['VALUE_ACTUAL_BASE_SALE_QTY'], ascending = False)

df_simulation_city_product_agg['MAPE_byMCH5CityLunarDay'] = abs(df_simulation_city_product_agg['VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityLunarDay'] - df_simulation_city_product_agg['VALUE_ACTUAL_BASE_SALE_QTY']) / df_simulation_city_product_agg['VALUE_ACTUAL_BASE_SALE_QTY'] 
df_simulation_city_product_agg['MAPE_byMCH5CityStoreTransactions'] = abs(df_simulation_city_product_agg['VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions'] - df_simulation_city_product_agg['VALUE_ACTUAL_BASE_SALE_QTY']) / df_simulation_city_product_agg['VALUE_ACTUAL_BASE_SALE_QTY'] 

df_simulation_city_product_agg

,CITY,PRODUCT_ID,VALUE_ACTUAL_BASE_SALE_QTY,VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityLunarDay,VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions,MAPE_byMCH5CityLunarDay,MAPE_byMCH5CityStoreTransactions
1949,HÀ NỘI,10012012,568404.00,765351.387205,757838.770065,0.346492,0.333275
1938,HÀ NỘI,10011650,544896.00,329590.745126,325719.182367,0.395131,0.402236
1980,HÀ NỘI,10167037,249980.00,150195.888989,151585.412136,0.399168,0.393610
2890,HỒ CHÍ MINH,10150217,236271.00,167328.137459,168481.458413,0.291796,0.286914
1946,HÀ NỘI,10011898,232825.00,261062.301130,259527.197596,0.121281,0.114688
...,...,...,...,...,...,...,...
6041,THỪA THIÊN HUẾ,10193978,1.00,0.096440,0.114025,0.903560,0.885975
1884,HÀ NAM,10196437,1.00,0.839297,0.659179,0.160703,0.340821
6056,THỪA THIÊN HUẾ,10196064,1.00,0.094313,0.332969,0.905687,0.667031
6401,TUYÊN QUANG,10230516,1.00,3.352191,2.268274,2.352191,1.268274
6273,TRÀ VINH,10196002,0.89,0.180823,0.187928,0.796828,0.788845

In [57]:
df_simulation_city_product_agg[:20]

,CITY,PRODUCT_ID,VALUE_ACTUAL_BASE_SALE_QTY,VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityLunarDay,VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions,MAPE_byMCH5CityLunarDay,MAPE_byMCH5CityStoreTransactions
1949,HÀ NỘI,10012012,568404.0,765351.387205,757838.770065,0.346492,0.333275
1938,HÀ NỘI,10011650,544896.0,329590.745126,325719.182367,0.395131,0.402236
1980,HÀ NỘI,10167037,249980.0,150195.888989,151585.412136,0.399168,0.393610
2890,HỒ CHÍ MINH,10150217,236271.0,167328.137459,168481.458413,0.291796,0.286914
1946,HÀ NỘI,10011898,232825.0,261062.301130,259527.197596,0.121281,0.114688
1974,HÀ NỘI,10150217,221891.0,95722.858124,95029.516768,0.568604,0.571729
2853,HỒ CHÍ MINH,10011650,159260.0,110764.107491,109370.918211,0.304508,0.313256
1924,HÀ NỘI,10011223,158359.0,114216.563903,115132.215626,0.278749,0.272967
1945,HÀ NỘI,10011891,157012.0,81587.328727,80424.111805,0.480375,0.487784
1942,HÀ NỘI,10011759,113154.0,56023.067609,55161.052957,0.504895,0.512513
1948,HÀ NỘI,10012008,112648.0,46361.336007,45938.682271,0.588441,0.592193
2834,HỒ CHÍ MINH,10011214,108780.0,82041.240175,84359.562516,0.245806,0.224494
5096,QUẢNG NINH,10011650,106647.0,82585.545354,80492.512633,0.225618,0.245244
2857,HỒ CHÍ MINH,10011759,105943.0,35333.602274,33433.892980,0.666485,0.684416
2865,HỒ CHÍ MINH,10012012,103039.0,116556.925745,115718.152603,0.131192,0.123052
2076,HÀ NỘI,10620864,94731.0,37050.183222,36130.028453,0.608891,0.618604
2618,HẢI PHÒNG,10011650,80647.0,49257.972188,47378.135392,0.389215,0.412525
1921,HÀ NỘI,10011215,80184.0,47216.302258,47103.057604,0.411151,0.412563
1922,HÀ NỘI,10011216,74185.0,52511.850101,52748.621425,0.292150,0.288958
1936,HÀ NỘI,10011639,71591.0,37861.388650,37831.581198,0.471143,0.471560

In [46]:
df_simulation_city_product_agg[:20][['MAPE_byMCH5CityLunarDay', 'MAPE_byMCH5CityStoreTransactions']].mean()

MAPE_byMCH5CityLunarDay             0.386055
MAPE_byMCH5CityStoreTransactions    0.388129
dtype: float64

In [56]:
df_simulation_store_product_agg[:20]

,CITY,STORE_ID,PRODUCT_ID,VALUE_ACTUAL_BASE_SALE_QTY,VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityLunarDay,VALUE_FORECAST_BASE_SALE_QTY_byMCH5CityStoreTransactions,MAPE_byMCH5CityLunarDay,MAPE_byMCH5CityStoreTransactions
31803,HÀ NỘI,1535,10012012,27519.0,55067.004547,50725.335244,1.001054,0.843284
119605,HÒA BÌNH,1648,10012012,25903.0,10284.110681,10702.022973,0.602976,0.586842
31252,HÀ NỘI,1530,10167037,19447.0,328.483298,299.795015,0.983109,0.984584
32081,HÀ NỘI,1541,10012012,13883.0,16167.585441,14860.412976,0.164560,0.070404
36702,HÀ NỘI,1698,10167037,13035.0,7798.855621,7417.423361,0.401699,0.430961
139330,HỒ CHÍ MINH,1527,10150217,12428.0,261.782863,240.485940,0.978936,0.980650
36423,HÀ NỘI,1673,10012012,11648.0,5639.641431,5183.400214,0.515827,0.554997
232328,TUYÊN QUANG,1601,10011650,11414.0,4684.861260,4361.305131,0.589551,0.617899
35388,HÀ NỘI,1661,10012012,11361.0,8568.329613,7877.314244,0.245812,0.306635
34968,HÀ NỘI,1657,10012012,11124.0,33288.911222,30543.373775,1.992531,1.745719
182519,LAI CHÂU,1695,10011650,11101.0,6187.388391,5813.388182,0.442628,0.476319
34419,HÀ NỘI,1653,10012012,11054.0,15756.649089,14558.545010,0.425425,0.317039
36181,HÀ NỘI,1671,10167037,11048.0,602.604427,551.939044,0.945456,0.950042
31497,HÀ NỘI,1532,10011650,10976.0,4711.196071,4311.169320,0.570773,0.607219
35127,HÀ NỘI,1658,10167037,10547.0,3462.292102,3172.001453,0.671727,0.699251
34857,HÀ NỘI,1656,10167037,10535.0,654.738143,602.548664,0.937851,0.942805
196728,NINH THUẬN,1540,10011759,10492.0,1347.079299,1249.764685,0.871609,0.880884
231697,TRÀ VINH,1593,10011759,10254.0,31.609818,26.073873,0.996917,0.997457
32596,HÀ NỘI,1569,10301075,9667.0,211.601555,197.829505,0.978111,0.979536
195501,NINH BÌNH,1537,10012012,9109.0,30157.212024,28005.670473,2.310705,2.074505

In [54]:
df_simulation_store_product_agg[:20][['MAPE_byMCH5CityLunarDay', 'MAPE_byMCH5CityStoreTransactions']].mean()

MAPE_byMCH5CityLunarDay             0.831363
MAPE_byMCH5CityStoreTransactions    0.802351
dtype: float64